version: '3.9'

services:
  app:
    image: ${DOCKERIMAGE_LATEST}
    ports:
      - "8333:8000"
    expose:
      - "8000"
    networks:
      - test-network
    env_file:
      - docker-image-ci.env

  tests:
    build:
      context: .
      dockerfile: test/Dockerfile.test
    depends_on:
      - app
    networks:
      - test-network
    environment:
      - APP_BASE_URL=http://app:8000

networks:
  test-network: