name: CI Workflow

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Load environment variables
        run: |
          cat docker-image-ci.env >> $GITHUB_ENV

      - name: Pull the latest Docker Image
        run: |
          docker pull ${{ env.DOCKERIMAGE_PULL }}

      - name: Run tests with docker-compose
        run: |
          docker compose up --abort-on-container-exit --exit-code-from tests

      - name: Clean up
        if: always()
        run: docker compose down

      - name: Notify success
        if: success()
        run: |
          echo "Tests passed successfully. Merging code changes..."
          exit 0  # Exit code indicates success

      - name: Notify failure
        if: failure()
        run: |
          echo "Tests failed, the code changes can't be merged"
          exit 1  # Exit code indicates failure

      # IF RUNNING FROM A SELF-HOSTED RUNNER, ENSURE gh CLI IS INSTALLED:
      # - name: Install GitHub CLI
      #   run: |
      #     curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      #     echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.
