name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - '/app/**'
      - '/test/**'
      - 'readme.md' # Readme modifications trigger CI pipeline for testing purposes
  pull_request:
    branches: [ main ]
    paths:
      - '/app/**'
      - '/test/**'
      - 'readme.md' # Readme modifications trigger CI pipeline for testing purposes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Load environment variables
      run: |
        cat docker-image-ci.env >> $GITHUB_ENV

    - name: Build the Docker Image
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        docker build ./app --file ${{ env.DOCKERFILE_PATH }} --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}-$TIMESTAMP --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:latest

    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker Image with Timestamp Tag
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}-$TIMESTAMP
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:latest