name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - '/app/**'
      - '/test/**'
      - 'readme.md' # Readme modifications trigger CI pipeline for testing purposes
  pull_request:
    branches: [ main ]
    paths:
      - '/app/**'
      - '/test/**'
      - 'readme.md' # Readme modifications trigger CI pipeline for testing purposes

env:
  DOCKER_REPO: fastapi-slim
  DOCKER_TAG: base
  DOCKERFILE_PATH: app/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract repo name
      run: echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY#*/})" >> $GITHUB_ENV

    - name: Get current timestamp
      run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Build the Docker Image
      run: |
        docker build ./app --file ${{ env.DOCKERFILE_PATH }} --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}-${{ env.TIMESTAMP }} --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:latest

    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker Image with Timestamp Tag
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}-${{ env.TIMESTAMP }}

    - name: Push the Docker Image with Latest Tag
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:latest

    - name: Set DOCKER_REPO environment variable (for CI Workflow)
      run: echo "DOCKER_REPO=${{ env.DOCKER_REPO }}" >> $GITHUB_ENV  # Add this line
